version: '3'

services:

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d/:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      default:
        aliases:
          - resource-provider.localhost.yarf.nl
          - resource-provider-api.localhost.yarf.nl
          - identity.localhost.yarf.nl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keycloak
      - resource-provider
      - resource-provider-api

  keycloak:
    # build: ./keycloak
    image: quay.io/keycloak/keycloak:latest
    command: [
      "start-dev",
      # "--help",
      # "-b", "0.0.0.0",
      "--import-realm",
      "--log-level=debug",
      "--metrics-enabled=true",
      "--db=postgres",
      "--db-url=postgres:5432",
      "--db-username=keycloak",
      "--db-password=keycloak",
      "--db-schema=keycloak",
      # "--verbose",
      # "-Dkeycloak.migration.action=import",   # Replace with 'export' in order to export everything
      # "-Dkeycloak.migration.provider=dir",
      # "-Dkeycloak.migration.dir=/opt/keycloak/data/import",
      # "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    ]
    environment:
      - KC_METRICS_ENABLED=true
      # - POSTGRES_DATABASE=keycloak
      # - POSTGRES_USER=keycloak
      # - POSTGRES_PASSWORD=password
      - KEYCLOAK_HOSTNAME=identity.localhost.yarf.nl
      # # Legacy linking functionality is used
      # - POSTGRES_PORT_5432_TCP_ADDR=postgres
      # - POSTGRES_PORT_5432_TCP_PORT=5432
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_LOGLEVEL=DEBUG
      # - KEYCLOAK_ADMIN=admin
      # - KEYCLOAK_ADMIN_PASSWORD=admin
      # # - JAVA_TOOL_OPTIONS=-Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.token_exchange=enabled  # Required to enable Token exchange feature in newer versions of Keycloak
    volumes:
      - ./keycloak/export:/opt/keycloak/data/import/
    networks:
      default:
        aliases:
          - keycloak

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    networks:
      default:
        aliases:
          - postgres

  resource-provider:
    build: ./resource-provider
    entrypoint: docker/entrypoint-dev.sh
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8001" ]
    volumes:
      - ./resource-provider:/usr/src/app
      - ./../:/usr/src/django-keycloak
      - ./../../python-keycloak-client:/usr/src/python-keycloak-client
      - ./nginx/certs/ca.pem:/usr/src/ca.pem
    networks:
      default:
        aliases:
          - resource-provider

  resource-provider-api:
    build: ./resource-provider-api
    entrypoint: docker/entrypoint-dev.sh
    command: [ "python", "manage.py", "runserver", "0.0.0.0:8002" ]
    volumes:
      - ./resource-provider-api:/usr/src/app
      - ./../:/usr/src/django-keycloak
      - ./nginx/certs/ca.pem:/usr/src/ca.pem
    networks:
      default:
        aliases:
          - resource-provider-api